# @package _global_

defaults:
  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

dataset: "conflab-dataset"

img_root_dir: "${env:HOME}/datasets/conflab-mm/frames/videoSegments"
ann_dir: "${env:HOME}/datasets/conflab-mm/pose"

create_coco: false
coco_json_path: "store/conflab_coco.json"
coco_json_path_train: "store/conflab_coco_train.json"
coco_json_path_test: "store/conflab_coco_test.json"
train_split: 0.8

model_zoo: "COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"

exp_name: "kp_base"
output_dir: "./ckpt/${exp_name}"

# train test split

train_dataset: ${dataset}_train
test_dataset: ${dataset}_test

num_workers: 4
num_classes: 1

eval_only: true
pretrained: true
resume: false

visualize: true
num_items: 10

num_gpus: 1
num_machines: 1
batch_size: 2
max_iters: 5000
learning_rate: 0.0005

size: [960, 540]

hydra:
  run:
    dir: .
  output_subdir: null
