# @package _global_

defaults:
  - _self_
  - mode: vis
  - task: keypoint
  - zoo: ${task}_R50_FPN

  - override hydra/hydra_logging: none
  - override hydra/job_logging: none

dataset: "conflab-dataset"
meta_dataset: "conflab-dataset"

img_root_dir: "${env:HOME}/datasets/conflab-mm/frames/videoSegments"
ann_dir: "${env:HOME}/datasets/conflab-mm/pose"

create_coco: false
force_register: false # NOTE fore re-register

coco_json_path: "store/conflab_coco.json"

split_path: ""
coco_json_prefix: ""
coco_json_path_train: "store/conflab_coco_train_${coco_json_prefix}.json"
coco_json_path_test: "store/conflab_coco_test_${coco_json_prefix}.json"

test_cam:
  - cam6 # use camera 6 as test camera

train_cam:
  - cam2
  - cam4
  - cam8
  - cam10

# model_zoo: "COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x.yaml"
# model_zoo_weights: "https://dl.fbaipublicfiles.com/detectron2/COCO-Keypoints/keypoint_rcnn_R_50_FPN_3x/137849621/model_final_a6e10b.pkl"

name: "kp_base"
output_dir: "./ckpt/${name}"
checkpoint: null # whether to load any pretrained checkpoint

train_dataset: ${dataset}_train
test_dataset: ${dataset}_test

log_dir: "logs"
log_prefix: ""

num_workers: 4
num_classes: 1

total_ann: null

# eval_only: true
# pretrained: false
# resume: false
# visualize: false
# num_items: 10

batch_size: 2
max_iters: 50000
learning_rate: 0.002

roi_thresh: 0.5

size: [960, 540]

# data creation
thresh_null_kp: 0.1 # upper limit for null values: if less than 10% are null values, pick the image
data_create_num_vis: 10
data_plot: false
total_ann_per_file: null

# ddp
machine_rank: 0
num_machines: 1
dist_url: "auto" #"tcp://127.0.0.1:3200"
num_gpus: 1
seed: 0
benchmark: false

hydra:
  run:
    dir: .
  output_subdir: null
